version: "3"
services:
  tongyiqwen-http:
    image: yoaken/tongyiqwen-http
    container_name: tongyiqianwen
    ports:
      - "20104:20104"
    volumes:
      - ./config.yaml:/app/tongyiqwen/config.yaml
      - ./preset.json:/app/tongyiqwen/preset.json
    environment:
      - GIN_MODE=release